# Default values of `FeatureExtractor` class arguments which are currently being used in API
target_month: 3
n_purchases: 2
perform_split: False
generation_type: 'continuous'
filtering_set: 'customers'
period: 60
subperiod: 15
# Model location on Weights&Biases
wandb_model_project: 'X-G-B-Classifier'
wandb_model_id: 'gnazdw35'
# Path where the model will be saved locally after it is loaded from Weights&Biases
model_path: 'service/app_api/configs'
# Miscellaneous params for hints mostly
customers_set_filtering_thresholds: '2021-06-01 00:00:00'