# Default values of `FeatureExtractor` class arguments which are currently being used in API
target_month: 3
n_purchases: 2
perform_split: False
generation_type: 'continuous'
filtering_set: 'customers'
period: 60
subperiod: 15
# Classification model location on Weights&Biases
wandb_classification_model_project: 'X-G-B-Classifier'
wandb_classification_model_id: 'w1vrxrjz'
# Clustering model centroids on Weights&Biases
wandb_clustering_model_project: 'K-Means'
wandb_clustering_model_id: 'clustering_report'
clusters_mapping:
  0: 'regular_drivers'
  1: 'passerbys'
  2: 'frequent_drivers'
  3: 'at_churn_risk'
# Path where the models will be saved locally after being downloaded from Weights&Biases
model_path: 'service/app_api/configs'
# Miscellaneous params for hints mostly
customers_set_filtering_thresholds: '2021-06-01 00:00:00'