version: "3"
services:
  fastapi:
    container_name: app-api
    build: ./app_api
    ports:
      - "8000:8000"
    networks:
      - fastapi-dash

  dash:
    container_name: app-ui
    build: ./app_ui
    ports:
      - "5050:80"
    networks:
      - fastapi-dash
    depends_on:
      - fastapi
    
networks:
  fastapi-dash:
    driver: bridge