# Primary keys represent the names of `FeatureExtractor` class constructor arguments
# This config contains default values of these corresponding arguments

lambda_features:
  # - 'initial_col': 'prodcategoryname'
  #   'feature_name': 'prodcatbroad'
  #   'lambda_func': "lambda x: 'fuel_qty' if x == 'FUELS' else 'car_wash_qty' if x == 'CAR WASH' else 'convenience_store_qty'"

  - 'initial_col': 'receiptdate'
    'feature_name': 'weekday'
    'lambda_func': "lambda x: 'weekend_qty' if x.day_name() in ['Saturday', 'Sunday'] else 'weekday_qty'"

  - 'initial_col': 'prodcatbroad'
    'feature_name': 'labour_cards_catalogue_consumables'
    'lambda_func': "lambda x: 1 if 'labour_cards_catalogue_consumables' in x else 0"


groupby_features:
  - 'groupcol': 'ciid'
    'aggcol': 'receiptdate'
    'aggfunc': "lambda x: ((x.min()+timedelta(days=30))-x.max()).days"
    'to_frame_name': 'recency'

  - 'groupcol': 'receiptid'
    'aggcol': 'prodcategoryname'
    'aggfunc': "lambda x: 0 if 'FUELS' in x.unique() else 1"
    'to_frame_name': 'full_non_fuel_purchase'


# Every new feature is added to the final dataframe through "pivoting", i.e. aggregating on customer level
customer_level_features:
  - 'columns': 'prodcatbroad'
    'values': 'qty'
    'index': 'ciid'
    'aggfunc': 'sum'

  - 'columns': 'peak_hour'
    'values': 'qty'
    'index': 'ciid'
    'aggfunc': 'sum'

  - 'columns': 'weekday'
    'values': 'qty'
    'index': 'ciid'
    'aggfunc': 'sum'

  - 'columns': 'fuel_type'
    'values': 'qty'
    'index': 'ciid'
    'aggfunc': 'sum'

  - 'columns': 'breaks'
    'values': 'qty'
    'index': 'ciid'
    'aggfunc': 'sum'
    'prefix': 'qty'

  - 'columns': null
    'values': 'target'
    'index': 'ciid'
    'aggfunc': 'mean'

  - 'columns': null
    'values': 'average_days_between_visits'
    'index': 'ciid'
    'aggfunc': 'mean'

  - 'columns': null
    'values': 'recency'
    'index': 'ciid'
    'aggfunc': 'mean'

  - 'columns': null
    'values': 'last_purchase_share'
    'index': 'ciid'
    'aggfunc': 'mean'

  - 'columns': null
    'values': 'labour_cards_catalogue_consumables'
    'index': 'ciid'
    'aggfunc': "lambda x: 1 if 1 in x.values else 0"

  - 'columns': null
    'values': 'full_non_fuel_purchase'
    'index': 'ciid'
    'aggfunc': "lambda x: 1 if 1 in x.values else 0"


# Do not forget to add here the names of the final new column(s)
current_features:
  - 'fuel_qty'
  - 'unleaded_95_qty'
  - 'peak_hours_qty'
  - 'usual_hours_qty'
  - 'weekday_qty'
  - 'weekend_qty'
  - 'qty_1-7'
  - 'qty_8-14'
  - 'qty_15-21'
  - 'qty_22-28'
  - 'average_days_between_visits'
  - 'recency'
  - 'last_purchase_share'
  - 'labour_cards_catalogue_consumables'
  - 'full_non_fuel_purchase'


train_test_split_params: 
  'test_size': 0.25
  'random_state': 571
  # Data is sorted by date => need to shuffle
  'shuffle': True
